/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ind.amirali;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration;

@SpringBootApplication(exclude = {JacksonAutoConfiguration.class})
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }
}
